spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://localhost/ms-security?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=Hongkong
    username: root
    password: 123456
  redis:
    host: localhost

server:
  port: 8089

logging:
  level:
    root: debug


